### ISSUE TITLE
Andere Städte und Ärzte

### ISSUE THREAD

**Issue by Lorold** [mi01/vaccine-booker-berlin#1]
Hey @mi01, der Code sieht wirklich gut aus! Ich habe mich auch zuvor mit dem Code von doctoshotgun beschäftigt. Gibt es bei Ihrem Code eine Möglichkeit statt Impfzentren in Berlin generell die gelisteten Ärzte bei doctolib bezüglich eines Impftermins zu buchen? Und somit auch die Suchstadt ändern?

Viele Grüße!

**Comment by mi01** [comment]
Hallo @Lorold , der Code von [Doctoshutgun](https://github.com/rbignon/doctoshotgun) funktioniert grundsätzlich auch mit der deutschen Doctolib-Webseite. Eigentlich müssen bloß die URLs anpasst werden, z.B. wird aus `https://www.doctolib.fr/vaccination-covid-19/($City)` dann halt `https://www.doctolib.de/impfung-covid-19-corona/($City)`. Ggf. gibt es auch noch kleine Unterschiede in Bezug auf die Formfelder, die bei der Buchung auszufüllen sind. Allerdings gibt es meiner Wahrnehmung nach, im Gegensatz zu Frankreich, in Deutschland bisher kaum freie Termine für Impfungen in Arztpraxen auf Doctolib, und wenn dann nur mit Einschränkungen, z.B. nur Altergruppe 40+ für AstraZeneca oder nur für Bestandspatienten.

Die Berliner Impfzentren sind allerdings ein Spezialfall, weshalb ich den Code von Doctoshutgun etwas weitergehend anpassen musste. Sie sind z.B. nicht über die Doctolib-Suche findbar, wenn man nach dem Behandlungsgrund "Covid19-Impfung" sucht. Und sie brauchen (bisher noch) Angaben zur Priorisierung und Telefonnr., was bei normalen Buchungen auf Doctolib nicht der Fall ist. Deshalb werde ich an dieser Stelle keine Option für eine Suche in anderen Städten einbauen. Mit ein wenig Aufwand ließe sich dies aber durch die Anpassung von Doctoshotgun realisieren. Eventuell wäre es sinnvoll bei Doctoshotun einen Parameter hinzuzufügen, der es möglich macht zwischen der deutschen und französischen Doctolib-Seite zu wählen.

Ich hoffe das beantwortet die Frage. Viele Grüße!

**Comment by Lorold** [comment]
Hallo @mi01, vielen Dank für Deine Antwort. Die URLs sowie die motives IDs habe ich angepasst. Doch was genau meint er mit der speciality_id': '5494'? Was wäre das Äquivalent? Und bei center = URL(r'/centre-de-sante/.*', CenterPage) bin ich mir unsicher, was ich dort genau einsetzen sollte. Hättest du einen Rat für mich?

Berliner Impfzentren sind momentan wirklich ein Spezialfall. Da stimme ich dir zu und habe es auch im Code nachvollziehen können. Ärzte werden zunehmend mehr Impfangebote machen, das ist m.E. auch schon auf doctolib bemerkbar. Leider sind die wenigen Termine unglaublich schnell vergriffen.

viele Grüße!

**Comment by mi01** [comment]
Hallo @Lorold , also zunächst sucht Doctoshotgun nach den Impfmöglichkeiten in der jeweiligen Stadt, die URL hierfür ist wie gesagt `https://www.doctolib.de/impfung-covid-19-corona/($City)`. Für jedes Suchergebnis werden dann die Details abgefragt, z.B.  `GET https://www.doctolib.de/search_results/2522878.json?limit=6&insurance_sector=public&ref_visit_motive_ids[]=6768,6936,7109,7978&speciality_id=5593&search_result_format=json`. Der Parameter `speciality_id` ist der Behandlungsgrund. Auf der dt. Doctolib-Seite ist der Behandlungsgrund Covid19-Impfung also mit der ID `5593` verknüpft. Die Antwort kommt dann jeweils als JSON und wird in `center` gespeichert. Für den genannten Request ist die Antwort dann das hier:

`{"total":0,"availabilities":[{"date":"2021-06-06","slots":[]},{"date":"2021-06-07","slots":[]},{"date":"2021-06-08","slots":[]},{"date":"2021-06-09","slots":[]},{"date":"2021-06-10","slots":[]},{"date":"2021-06-11","slots":[]}],"next_slot":"2021-07-10",
"search_result":{"id":2522878,"is_directory":false,"address":"Alt-Buckow 9-11","city":"Berlin","zipcode":"12349","link":"/gemeinschaftspraxis/berlin/gemeinschaftspraxis-alt-buckow","cloudinary_public_id":"sy95ouvfwm8bxtxbvkai","profile_id":268972,"exact_match":null,"priority_speciality":false,"first_name":null,"last_name":"Gemeinschaftspraxis Alt Buckow","name_with_title":"Gemeinschaftspraxis Alt Buckow","speciality":null,"organization_status":"Gemeinschaftspraxis","position":{"lat":52.4230522,"lng":13.4355342},"place_id":null,"telehealth":true,"visit_motive_id":2794293,"visit_motive_name":"Erstimpfung Covid-19 (AstraZeneca)","agenda_ids":[461911,461913],"booking_temporary_disabled":false,"resetVisitMotive":true,"toFinalizeStep":false,"toFinalizeStepWithoutState":false,"url":"/gemeinschaftspraxis/berlin/gemeinschaftspraxis-alt-buckow?insurance_sector=public"}}`

Diese Ergebnisse werden dann alle der Reihe nach durchprobiert. Die ursprüngliche Initialisierung mit `center = URL(r'/centre-de-sante/.*', CenterPage)` ist also nicht relevant, weil die Variable sowieso durch das jeweilige Suchergebnis überschrieben wird.

Allgemein kannst du dies alles gut nachvollziehen, wenn du im Browser die Entwicklertools öffnest und diesen manuell Vorgang wiederholst. Im Reiter Network kannst du genau sehen, welche Request verschickt werden und was als Antwort kommt.

**Comment by Lorold** [comment]
Hallo @mi01, vielen Dank für deine Hilfe. Ich habe es hinbekommen und es läuft. Vielen Dank!
