### ISSUE TITLE
  Error: 500 Server Error: Internal Server Error

### ISSUE THREAD

**Issue by Kuhno92** [mi01/vaccine-booker-berlin#4]
I get an  Error: 500 Server Error: Internal Server Error when the script to actually make the booking.
The dry run variant runs fine

**Comment by mi01** [comment]
The script is still adjusted to the situation in the late summer, when there were different vaccination centers and no booster shot. I guess Doctolib slightly changed the booking procedure, but i will have a look if this can be easily fixed.

**Comment by mi01** [comment]
Last commit bc53066f0ba139c73f25d3968373ca08f635c10b should solve most problems now.

**Comment by Kuhno92** [comment]
Thanks for updating the code to support booster vaccination. But the Error 500 still exists when the script tries to book a found slot :(

**Comment by mi01** [comment]
I was able to book a slot with the script. Can you provide the parameters you were using? And did you filled out all profile informations for the person for that you want to book?

**Comment by Kuhno92** [comment]
These are my start parameters: booster USERNAME PASSWORT --start-date 2021-12-03 --time-window 100

I deleted the patient on Doctolib and created a new one. 
Now I get always 422 Client Error: Unprocessable Entity.
I double checked all the fields. But can not figure out what is wrong there :(

**Comment by Kuhno92** [comment]
figured out that it has to be something with the phone number or email of the Doctolib patient. If I leave this fields empty, I get the 500 Internal Server Error. If I put a mobile number and email for this patient, I get the 422 Unprocessable Entity Error

**Comment by Kuhno92** [comment]
ok finally found the problem. One has to go to its profile on Doctolib and under "Identity" one has to specify which patient owns this account. Then the error is gone :) This issue can be closed then

**Comment by mi01** [comment]
Great that you figured out the problem. I updated the script, so that the telephone number and the email is not necessary for booking anymore.
