### ISSUE TITLE
Request blocked by CloudFlare

### ISSUE THREAD

**Issue by rekado** [mi01/vaccine-booker-berlin#5]
```
python3 vaccine-booker-berlin/booker.py --debug booster my-username "my password"
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.doctolib.de:443
DEBUG:urllib3.connectionpool:https://www.doctolib.de:443 "GET /sessions/new HTTP/1.1" 503 None
INFO:browser:Response saved to c21c2662ac85486292dbfa94da0a82c8
:::  Request blocked by CloudFlare. Try again!
Could not login!
```

**Comment by mi01** [comment]
Cloudscraper is sometimes not able to surmount the CloudFlare protection. In this case only waiting some minutes and retrying is the only solution. Sometime this process has to be repeated several times before a login attempt is successful.

**Comment by rekado** [comment]
Turns out that it was this patched version of cloudscraper that didn't manage to get around CloudFare.  With an upgrade and adjusted patches it works now.  Thanks!
